name: "EVN VN"
description: "Add-on EVN VN in Home Assistant"
url: "https://github.com/smarthomeblack/hass-addon"
version: "2025.6.17"
slug: "evnvn"
init: false
ingress: true
ingress_port: 1093
panel_icon: mdi:transmission-tower-import
map:
  - config:rw
  - data:rw
options:
  accounts_json: >
    [
      {"userevn": "tài khoản evn", "passevn": "mật khẩu evn", "server": ""}
    ]
  gemini_api_key: "API_KEY"
  gemini_model: "gemini-2.0-flash"

ports:
  1093/tcp: null
schema:
  accounts_json: str
  gemini_api_key: str
  gemini_model: str

arch:
  - amd64
  - aarch64
image: "ghcr.io/smarthomeblack/evnvn-{arch}"
