name: "EVN VN"
description: "Add-on EVN VN in Home Assistant"
url: "https://github.com/smarthomeblack/hass-addon"
version: "2025.6.7a"
slug: "evnvn"
init: false
map:
  - config:rw
  - data:rw
options:
  accounts_json: >
    [
      {"userevn": "tài khoản evn", "passevn": "mật khẩu evn", "ngaydauky": "1"}
    ]
  mqtt_server: "192.168.1.22"
  mqtt_port: 1883
  mqtt_username: "admin"
  mqtt_password: "12345678"
  mqtt_topic_prefix: "homeassistant"
  gemini_api_key: "API_KEY"
  gemini_model: "gemini-2.0-flash"
  ngaydauky: "1"
ports:
  1093/tcp: null
schema:
  accounts_json: str
  mqtt_server: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
  gemini_api_key: str
  gemini_model: str
  ngaydauky: str

arch:
  - amd64
  - aarch64
image: "ghcr.io/smarthomeblack/evnvn-{arch}"
