name: "Zalo Hass Addon"
description: "Zalo messaging backend for Home Assistant (Node.js/Express)"
url: "https://github.com/smarthomeblack/hass-addon"
version: "1.0.0"
slug: "zalo"
init: false
ingress: true
ingress_port: 1094
panel_icon: mdi:chat
panel_title: "Zalo"
map:
  - config:rw
  - data:rw
host_network: true
hassio_api: true
hassio_role: "admin"
ports:
  1094/tcp: null
arch:
  - amd64
image: "ghcr.io/smarthomeblack/zalo-{arch}"
