name: "EVN Miền Nam"
description: "Add-on EVN Miền Nam in Home Assistant"
url: "https://github.com/smarthomeblack/hass-addon"
version: "2025.6.6"
slug: "npcsg"
init: false
map:
  - config:rw
options:
  accounts_json: >
    [
      {"usernpc": "tài khoản evn", "passnpc": "mật khẩu evn"}
    ]
  mqtt_server: "192.168.1.22"
  mqtt_port: 1883
  mqtt_username: "admin"
  mqtt_password: "12345678"
  mqtt_topic_prefix: "homeassistant"
  gemini_api_key: "API_KEY"
  gemini_model: "gemini-2.0-flash"
  ngaydauky: "15"
ingress: true
ingress_port: 1093
schema:
  accounts_json: str
  mqtt_server: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
  gemini_api_key: str
  gemini_model: str
  ngaydauky: str

arch:
  - amd64
  - aarch64
image: "ghcr.io/smarthomeblack/npcsg-{arch}"
