name: "EVN VN"
description: "Add-on EVN VN in Home Assistant"
url: "https://github.com/smarthomeblack/hass-addon"
version: "2025.6.22"
slug: "evnvnbeta"
init: false
ingress: true
ingress_port: 1093
panel_icon: mdi:transmission-tower-import
map:
  - config:rw
  - data:rw

ports:
  1093/tcp: null
schema:
  accounts_json: str
  gemini_api_key: str
  gemini_model: str

arch:
  - amd64
image: "ghcr.io/smarthomeblack/evnvnbeta-{arch}"
